#!/bin/bash
prev=`pwd`
cd $HOME/.vim/bundle
git clone https://github.com/ajh17/VimCompletesMe
git clone https://github.com/ajh17/vim-fist
git clone https://github.com/dahu/Vimple
git clone https://github.com/dahu/VimFindsMe
git clone https://github.com/AndrewRadev/splitjoin.vim
git clone https://github.com/davidhalter/jedi-vim
git clone https://github.com/godlygeek/tabular
git clone https://github.com/mattn/emmet-vim
git clone https://github.com/Rip-Rip/clang_complete
git clone https://github.com/tommcdo/vim-exchange
git clone https://github.com/tpope/vim-commentary
git clone https://github.com/tpope/vim-dispatch
git clone https://github.com/tpope/vim-endwise
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/tpope/vim-obsession.git
git clone https://github.com/tpope/vim-repeat
git clone https://github.com/tpope/vim-surround
cd $prev
