#!/bin/sh
echo "-- Installing vim --"
hg clone https://code.google.com/p/vim/ && cd vim
./configure --with-features=huge --enable-multibyte --enable-pythoninterp --enable-perlinterp --prefix=/usr
make && sudo make install
