#!/usr/bin/env bash

bold=`tput bold`
norm=`tput sgr0`

echo -e "\n${bold}==> This script will automatically install essential tools and"
echo -e "link files from this folder to $HOME\n"
echo "==> Do you wish to proceed?${norm}"
select yn in "Yes" "No"; do
case $yn in
    Yes ) break;;
    No) echo "Okay stopping..." && exit;;
esac
done

# OS X specific config
if [ `uname` == "Darwin" ]; then
    echo -e "${bold}Checking if Homebrew is installed...${norm}"
    if [ ! -x /usr/local/bin/brew ]; then
        echo -e "${bold}\nHomebrew not installed. Installing it now...${norm}"
        ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    else
        echo -e "Homebrew is already installed."
    fi

    # Install homebrew apps
    echo -e "\n${bold}Installing homebrew apps (Go get a coffee)...${norm}"
    brew bundle $HOME/dotfiles/
    echo -e "\n${bold}Done installing homebrew apps!"

    echo -e "\n${bold}Setting up OS X defaults tricks...${norm}"
    defaults write com.apple.Finder QLEnableTextSelection -bool true
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    defaults write NSGlobalDomain KeyRepeat -int 0
    defaults write com.apple.dock expose-animation-duration -float 0.1

    # Slate
    echo "${bold}Linking slate...${norm}"
    /bin/ln -sfv ~/dotfiles/.slate $HOME

    # Vim
    echo "${bold}Linking vim...${norm}"
    /bin/ln -sfv ~/dotfiles/.vimrc $HOME
    /bin/ln -sFv ~/dotfiles/.vim $HOME
    mkdir -p $HOME/.vim/backup/undo

    # Install Vim plugins
    if [ -d ~/.vim/bundle/Vundle.vim ]; then
        echo -e "\n${bold}Vundle is already installed. Skipping...${norm}"
        echo -e "\n${bold}Updating Vim plugins instead...${norm}"
        sleep 3
        vim +PluginUpdate +qa
        echo -e "\n${bold}Vim plugins have been brought up to date.${norm}"
    else
        echo "Cloning Vundle..."
        rm -rf ~/.vim/bundle/ ; git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
        mkdir -p ~/.vim/backup/undo
        vim +PluginInstall +qa
        echo "${bold}Vim plugins were installed!${norm}"
    fi

    # Zsh
    echo "${bold}Linking zsh...${norm}"
    cd $HOME
    /bin/ln -sFv ~/dotfiles/.zsh
    /bin/ln -sfv ~/dotfiles/.zshrc
    /bin/ln -sfv ~/dotfiles/.zshenv
    rm -rf ~/.zsh/zsh-* && rm -rf ~/.zsh/opp.zsh
    echo "${bold}Cloning zsh plugins...${norm}"
    cd ~/.zsh
    git clone https://github.com/zsh-users/zsh-history-substring-search.git
    git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
    git clone https://github.com/hchbaw/opp.zsh.git && cd $HOME

    # Tmux
    echo "${bold}Linking tmux...${norm}"
    /bin/ln -sfv ~/dotfiles/.tmux.conf $HOME

    # Git stuff
    echo "${bold}Linking tig...${norm}"
    /bin/ln -sfv ~/dotfiles/.tigrc $HOME
    echo "${bold}Linking git templates...${norm}"
    /bin/ln -sFv ~/dotfiles/.git_template/ $HOME

    # User scripts
    echo "${bold}Linking user scripts...${norm}"
    /bin/ln -sFv ~/dotfiles/.bin $HOME

    echo -e "\n${bold}Done!${norm}"
fi
