#!/usr/bin/env bash
set -e

bold=`tput bold`
norm=`tput sgr0`

echo -e "\n${bold}==> This script will automatically install essential tools and"
echo -e "link files from this folder to $HOME\n"
echo "==> Do you wish to proceed?${norm}"
select yn in "Yes" "No"; do
case $yn in
    Yes ) echo "Okay, proceeding..." && break;;
    No) echo "Okay, stopping..." && exit;;
esac
done

# OS X specific config
if [ `uname` == "Darwin" ]; then
    echo -e "${bold}Checking if Homebrew is installed...${norm}"
    if [ ! -x /usr/local/bin/brew ]; then
        echo -e "${bold}\nHomebrew not installed. Installing it now...${norm}"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        echo -e "Homebrew is already installed."
    fi

    # Install homebrew apps
    echo -e "\n${bold}Installing homebrew apps (Go get a coffee)...${norm}"
    brew install ag aspell fasd chruby ruby-install reattach-to-user-namespace tmux
    brew install git --without-completions --with-pcre --with-brewed-curl --with-brewed-openssl
    brew install grep --default-names
    brew install python python3
    brew install vim --disable-nls --without-ruby --override-system-vi
    brew install weechat --with-aspell --with-lua --with-perl --with-python --with-ruby
    echo -e "\n${bold}Done installing homebrew apps!"

    echo -e "\n${bold}Setting up OS X defaults...${norm}"
    mkdir $HOME/.cache
    defaults write com.apple.Finder QLEnableTextSelection -bool true
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    defaults write NSGlobalDomain KeyRepeat -int 0
    defaults write com.apple.dock expose-animation-duration -float 0.15

    # Link iCloud Drive to $HOME for easy access.
    /bin/ln -sFv ~/Library/Mobile\ Documents/com~apple~CloudDocs ~/iCloudDrive

    # Vim
    echo "${bold}Linking vim...${norm}"
    /bin/ln -sfv ~/dotfiles/.vimrc $HOME
    /bin/ln -sFv ~/dotfiles/.vim $HOME
    mkdir -p ~/.vim/backup/undo
    if [ ! -d ~/.vim/bundle/ ]; then
        mkdir ~/.vim/bundle
    fi
    . ~/Library/Mobile\ Documents/com~apple~CloudDocs/Vim/vimutil/install_bundles

    # Zsh
    echo "${bold}Linking zsh...${norm}"
    cd $HOME
    /bin/ln -sFv ~/dotfiles/.zsh
    /bin/ln -sfv ~/dotfiles/.zshrc
    /bin/ln -sfv ~/dotfiles/.zshenv
    cd ~/dotfiles && git submodule update --init --recursive && cd $HOME

    # Tmux
    echo "${bold}Linking tmux...${norm}"
    /bin/ln -sfv ~/dotfiles/.tmux.conf $HOME

    # Git stuff
    echo "${bold}Linking tig...${norm}"
    /bin/ln -sfv ~/dotfiles/.tigrc $HOME
    echo "${bold}Linking git templates...${norm}"
    /bin/ln -sFv ~/dotfiles/.git_template/ $HOME

    # User scripts
    echo "${bold}Linking user scripts...${norm}"
    /bin/ln -sFv ~/dotfiles/.bin $HOME

    echo -e "\n${bold}Done!${norm}"
fi
